// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rymltjwdinnwpsebfgdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5bWx0andkaW5ud3BzZWJmZ2RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDU3ODAsImV4cCI6MjA3NDIyMTc4MH0.zV_pyOydawUO1teQn2biMnMU_QYc5rHGjDsZN0axB2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});